config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home', to: redirect('/')
  get 'home/people/:id' => 'people#home_person', as: :home_person
  get 'home/quotes/:id' => 'quotes#home_quote', as: :home_quote
  get 'people/select' => 'people#select', as: :person_select
  get 'people/:id/home' => 'people#person_home', as: :person_home
  post 'people/:id/create_quote'=> 'quotes#create', as: :create_quote
  get 'people/:id/detail' => 'people#detail', as: :person_detail

  resources :quotes

  get 'login/' => 'sessions#new', as: :login
  post 'login/' => 'sessions#create'
  delete 'logout/' => 'sessions#destroy', as: :logout
  
  resources :people do
    resources :quotes
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :quote
  belongs_to :commenter, :class_name => "Person", :foreign_key => :commenter_id
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_secure_password
  validates_uniqueness_of :username
  validates :name, :username, presence: true
  has_many :spoken_quotes, :class_name => "Quote", :foreign_key => :speaker_id,:dependent => :destroy
  has_many :posted_quotes, :class_name => "Quote", :foreign_key => :poster_id, :dependent => :destroy
  has_many :comments, :class_name => "Comment", :foreign_key => :commenter_id, :dependent => :destroy
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :speaker, :class_name => "Person", :foreign_key => :speaker_id
  belongs_to :poster, :class_name => "Person", :foreign_key => :poster_id
  has_many :comments, :dependent => :destroy
  validates :speaker_id, :body, :poster_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_person, :logged_in?

  def current_person
    @current_person ||= Person.find(session[:person_id]) if session[:person_id]
  end

  def logged_in?
    !current_person.nil?
  end

  def correct_quote_person
    quote = Quote.find(params[:id])
    if quote.poster_id == current_person.id || quote.speaker_id == current_person.id
    else
      flash[:error] = "You do not have permission to access that page."
      redirect_to root_path
    end
  end

  def correct_person
    person = Person.find(params[:id]) || Person.find(params[:person_id])
    if person.id == current_person.id
    else
      flash[:error] = "You do not have permission to access that page."
      redirect_to root_path
    end
  end

  def require_login
    if current_person.nil?
      flash[:error] = "You must be logged in to complete that action."
      redirect_to login_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  private

  def comment_params
    params.permit(comment:[:body, :commenter_id, :quote_id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :get_people
  before_action :get_quotes

  def get_people
    @people = Person.all
  end

  def get_quotes
    @quotes = Quote.all
  end

  def index
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :get_people
  before_action :get_quotes
  before_action :require_login, only: [:edit, :update, :destroy]
  before_action :correct_person, only: [:edit, :update, :destroy]


  def create
    @person = Person.new(person_params)
    if @person.save
      flash[:success] = "You have successfully registered for this site."
      redirect_to :controller => 'sessions', :action => 'new'
    else
      render :new
    end
  end

  def destroy
    p = Person.find(params[:id])
    p.destroy
    reset_session
    flash[:error] = "You are no longer a registered user of this site."
    redirect_to home_path
  end

  def get_people
    @people = Person.all
  end

  def get_quotes
    @quotes = Quote.all
  end

  def home_person
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def detail
    @person = Person.find(params[:id])
  end

  def person_home
    @new_quote = Quote.new
    @person = Person.find(params[:id])
  end

  def select
    redirect_to person_home_path(params[:person][:id])
  end

  private

  def person_params
    params.require(:person).permit(:name, :bio, :username, :password, :password_confirmation)
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :require_login, only: [:new, :edit, :create, :update, :destroy]
  before_action :correct_quote_person, only: [:edit, :update, :destroy]

  def create
    Quote.create(
    body: quote_params[:quote][:body],
    speaker_id: quote_params[:quote][:speaker_id],
    poster_id: current_person.id)
    redirect_to person_home_path(current_person)
  end

  def destroy
    id = params[:id]
    Quote.destroy(id)
    redirect_to person_detail_path(current_person.id)
  end

  def edit
    @quote = Quote.find(params[:id])
    @person = Person.find(@quote.poster_id)
    @people_options = Person.all.map{|p| [ p.name, p.id ] }
  end

  def get_quote
    @quote = Quote.find(params[:id])
  end

  def home_quote
    @quote = Quote.find(params[:id])
  end

  def new
    @quote = Quote.new
    @people_options = Person.all.map{|p| [ p.name, p.id ] }
  end

  def show
    @quote = Quote.find(params[:id])
  end

  def update
    @quote = Quote.find(params[:id])
    @quote.update(quote_params[:quote])
    redirect_to person_detail_path(current_person.id)
  end

  private

  def quote_params
    params.permit(quote:[:body, :speaker_id, :poster_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    data = params[:session_data]
    @person = Person.find_by_username(data[:username])
    if !@person.nil? && @person.authenticate(data[:password])
      session[:person_id] = @person.id
      flash[:success] = "You are now logged in."
      redirect_to root_path
    else
      flash.now[:error] = "Invalid username and password combination."
      render :new
    end
  end

  def destroy
    @current_person = nil
    session[:person_id] = nil
    flash[:success] = "You are now logged out."
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    case flash_type
      when "success"
        "alert-success"
      when "error"
        "alert-danger"
      when "alert"
        "alert-block"
      when "notice"
        "alert-info"
      else
        flash_type.to_s
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<div class= "stickypage">
  <h1 class="stickypage">Quotehort Four</h1>
  <section>
    <ul class= "stickynotes_container">
      <% @quotes.each do |quote| %>
        <li class="stickynote ">
              <%= link_to "#{quote.body}", home_quote_path(quote), :class => "stickyquote" %>
              <%= link_to "~#{quote.speaker.name}", home_person_path(quote.speaker), :class => "stickyspeaker" %>
        </li>
      <% end %>
    </ul>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>QuoteBoard</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1" charset="utf-8">
  </head>
  <body>
      <header class="container-fluid menu-holder">

        <div class="menu-button-holder hamburger dropdown-toggle">
          <div class= "btn btn-default menu-button", id= "hamburger">
              <span class="glyphicon glyphicon-menu-hamburger menu-glyph"></span>
          </div>
        </div>

        <div class="menu dropdown hidden">
          <div class="menu-button-holder">
            <%= link_to root_path, class: "btn btn-default menu-button" do %>
              <span class="glyphicon glyphicon-home menu-glyph"></span>
              <span class="menu-word">Home</span>
            <% end %>
          </div>

          <div class="menu-button-holder">
            <div class="btn btn-default menu-button">
              <span class="glyphicon glyphicon-user menu-glyph"></span>
              <%= collection_select :person, :id, Person.all, :id, :name, {prompt: "People"}, {class: "menu-word", onchange: "window.location='/people/'+this.value+'/detail'" } %>
            </div>
          </div>

          <% if logged_in? %>
            <div class="menu-button-holder">
              <div class= "btn btn-default menu-button", id= "new_quote_button">
                <%= link_to new_quote_path do %>
                  <span class="glyphicon glyphicon-pencil menu-glyph"></span>
                  <span class="menu-word">New Quote</span>
                <% end %>
              </div>
            </div>

            <div class="menu-button-holder">
              <%= link_to person_detail_path(current_person.id), class: "btn btn-default menu-button" do %>
                <span class="glyphicon glyphicon-tasks menu-glyph"></span>
                <span class="menu-word">My details</span>
              <% end %>
            </div>

          <% end %>

          <div class="menu-button-holder">
             <% if logged_in? %>
              <div class="btn btn-default menu-button">
                <%= link_to logout_path, class: "menu-word", method: :delete do %>
                  <span class="glyphicon glyphicon-user menu-glyph"></span>
                  <span class="menu-word">Logout</span>
                <% end %>
              </div>
            <% else %>
              <div class="btn btn-default menu-button">
                <%= link_to login_path, class: "menu-word" do %>
                  <span class="glyphicon glyphicon-user menu-glyph"></span>
                  <span class="menu-word">Login</span>
                <% end %>
              </div>
              <%= link_to new_person_path, class: "btn btn-default menu-button" do %>
                <span class="glyphicon glyphicon-plus menu-glyph"></span>
                <span class="menu-word">New Person</span>
              <% end %>
            <% end %>
          </div>
      </div>
    </header>
    <div class="container">
      <div class="top-margin">
        <%= render partial: "shared/flash_messages", flash: flash %>
        <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/people/detail.html.erb
<div class="text-center container">
  <div class="detailholder">
    <% if logged_in? && @person.id == current_person.id %>
      <h1 class="detail">Hi, <%= @person.name %>!</h1>
      <h3>You've said...</h3>
    <% else %>
      <h3><%= @person.name.capitalize %> has said...</h3>
    <% end %>


    <table class="table detailtable">
      <% @person.spoken_quotes.each do |quote| %>
        <tr>
          <% if logged_in? && (quote.poster_id == current_person.id || quote.speaker_id == current_person.id) %>
            <td class= buttondata>
              <%= button_to "✐", edit_person_quote_path(@person.id, quote.id), method: :get, class: "quote_button" %>
            </td>
            <td class= buttondata>
              <%= button_to "✖", person_quote_path(@person.id, quote.id), method: :delete, class: "quote_button", data: { confirm: 'Are you sure?' } %>
            </td>
          <% end %>
          <td class="quote">
            <%= quote.body %>
          </td>
          <td class="name">
            posted by <%= quote.poster.name %>
          </td>
          <td class="date">
           <%= quote.created_at.strftime("%m/%d/%Y") %>
          </td>
        </tr>
     <% end %>
   </table>

   <% if logged_in? && @person.id == current_person.id %>
      <h3>You've heard...</h3>
   <% else %>
      <h3><%= @person.name.capitalize %> has heard...</h3>
    <% end %>

    <table class="table detailtable">
      <% @person.posted_quotes.each do |quote| %>
        <tr>
          <% if logged_in? && (quote.poster_id == current_person.id || quote.speaker_id == current_person.id) %>
            <td>
              <%= button_to "✐", edit_person_quote_path(@person.id, quote.id), method: :get, class: "quote_button" %>
            </td>
            <td class= buttondata>
              <%= button_to "✖", person_quote_path(@person.id, quote.id), method: :delete, class: "quote_button", data: { confirm: 'Are you sure?' } %>
            </td>
          <% end %>
          <td>
            <%= quote.body %>
          </td>
          <td>
            from <%= quote.speaker.name %> on <%= quote.created_at.strftime("%m/%d/%Y")  %>
          </td>
      </tr>
   <% end %>
   </table>

  <% if logged_in? && @person.id == current_person.id %>
  <div class="btn btn-default self_destruct_button">
    <span class="glyphicon glyphicon-remove-sign menu-glyph"></span>
    <%= link_to "Self destruct",  { :controller=> "people", :action => :destroy, :id => @person.id}, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
  <% end %>

</div>

app/views/people/home_person.html.erb
<div class="text-center container">
  <h1><%= @person.name %></h1>
  <h3><%= @person.bio %></h3>
  <h2>Said by <%= @person.name %></h2>
</div>
<div class="text-center container">
  <table class="table">
    <% @person.spoken_quotes.each do |quote| %>
  <tr>
    <td>
      <%= quote.body %>
    </td>
    <td>
      from <%= quote.poster.name %> at <%= quote.created_at %>
    </td>
 </tr>
 <% end %>
</table>
</div>

<div class="text-center container">
<h2>Heard by <%= @person.name %></h2>
</div>

<div class="text-center container">
  <table class="table">
    <% @person.posted_quotes.each do |quote| %>
  <tr>
    <td>
      <%= quote.body %>
    </td>
    <td>
      Said by <%= quote.speaker.name %> at <%= quote.created_at %>
    </td>
 </tr>
 <% end %>
</table>
</div>

<nav class="text-center container">
  <%= link_to "Back to Main", home_path %>
</nav>

app/views/people/new.html.erb
<div class="container">
  <div class= "row">
      <% if @person.errors.any? %>
      <div class= "new-person-errors">
        <div id="error_explanation">
          <ul>
            <% @person.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </div>
      <% end %>
    <div class= "col-md-4 new-person">
      <h2>New Person</h2>
      <%= form_for @person do |f| %>
        <div class="form-group">
          <%= f.label :username %>
          <%= f.text_field :username, :required => true, :class=> "form-control" %>

          <%= f.label :name %>
          <%= f.text_field :name, :required => true, :class=> "form-control" %>

          <%= f.label :bio %>
          <%= f.text_area :bio, :required => true, :class=>"form-control" %>

          <%= f.label :password %>
          <%= f.password_field :password, :required => true, :class=>"form-control" %>

          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, :required => true, :class=>"form-control" %>
        </div>

        <div class="actions bottom-margin text-center" >
          <%= f.submit "Create person", :class => 'btn btn-primary',:id=> 'create-person-button' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/people/person_home.html.erb
<div class= "stickypage">
  <h1 class="stickypage">Quotehort Four</h1>
  <section>
    <ul class= "stickynotes_container">
      <% @quotes.each do |quote| %>
        <li class="stickynote ">
              <%= link_to "#{quote.body}", home_quote_path(quote), :class => "stickyquote" %>
              <%= link_to "~#{quote.speaker.name}", home_person_path(quote.speaker), :class => "stickyspeaker" %>
        </li>
      <% end %>
    </ul>
  </section>
</div>

app/views/quotes/_form.html.erb
<%= form_for @quote do |f| %>
  <div class="form-group">
    <%= f.label :body, "Quote: " %>
    <%= f.text_area :body, :required => true, :class=> "form-control" %>
    <br>
    <%= f.label "Speaker: " %>
    <%= f.select(:speaker_id, @people_options, {prompt: "Select"}, :required => true) %>


  </div>

  <div class="actions bottom-margin text-center" >
    <%= f.submit :class => 'btn btn-primary',:id=> 'create-person-button' %>
  </div>
</div>
<% end %>s

app/views/quotes/edit.html.erb
<div class="container">
  <div class= "row">
    <div class= "col-md-4 new-person">
      <h2>Edit Quote</h2>
      <%= render partial: 'form' %>
  </div>
</div>

app/views/quotes/home_quote.html.erb
<section class="text-center container">
  <h1><%= @quote.body %></h1>
  <h2>~<%= @quote.speaker.name %><h2>
  <h3>overheard by <%= @quote.poster.name %><h3>
</section>

<div class="text-center container">
  <table class="table">
    <% @quote.comments.each do |comment| %>
  <tr>
    <td>
      <%= comment.body %>
    </td>
    <td>
      <%= comment.commenter.name %> at <%= comment.created_at %>
    </td>
 </tr>
 <% end %>
</table>
  <% if logged_in? && (@quote.poster_id == current_person.id || @quote.speaker_id == current_person.id) %>
    <%= link_to "Edit", edit_quote_path(@quote), :class => 'btn btn-primary' %>
    <%= link_to 'Delete', "/quotes/#{@quote.id}", method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
  <% end %>
</div>

app/views/quotes/new.html.erb
<div class="container">
  <div class= "row">
    <div class= "col-md-4 new-person">
      <h2>New Quote</h2>
      <%= render partial: 'form' %>
  </div>
</div>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>